# secret.yaml
# Content for /resources/secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: resource-name
  labels:
    app: component-name
    version: v1.0.0
    component: secret
spec:
  type: Opaque
  data:
    username: dXNlcm5hbWU=
    password: cGFzc3dvcmQ=