"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.createDefaultSettings = void 0;
// Default settings factory
const createDefaultSettings = () => ({
    autoSave: true,
    darkMode: false,
    lineNumbers: true,
    wordWrap: false,
    autoRefreshContexts: true,
    defaultNamespace: "default",
    baseDirectory: "",
    kubeConfigPath: "",
    gitRepositories: [],
    editorSettings: {
        fontSize: 14,
        fontFamily: "Monaco, 'Courier New', monospace",
        tabSize: 2,
        insertSpaces: true,
        wordWrap: "off",
        wordWrapColumn: 80,
        minimap: true,
        lineNumbers: "on",
        folding: true,
        autoIndent: "advanced",
        formatOnSave: true,
        formatOnPaste: false,
        trimTrailingWhitespace: true,
        insertFinalNewline: true,
        theme: "dark",
        bracketPairColorization: true,
        showWhitespace: "none",
    },
    kubernetesSettings: {
        defaultContext: "",
        defaultNamespace: "default",
        autoSwitchContext: false,
        validateResources: true,
        dryRunByDefault: false,
        showSystemNamespaces: false,
        refreshInterval: 30,
        timeoutDuration: 30,
        maxLogLines: 1000,
        followLogs: true,
        contexts: [],
    },
    securitySettings: {
        enableSecureStorage: true,
        encryptLocalData: false,
        sessionTimeout: 60,
        requireAuthForSensitiveOps: true,
        auditLogging: false,
        allowRemoteConnections: false,
        trustedHosts: [],
        sslVerification: true,
    },
    uiSettings: {
        theme: "system",
        accentColor: "#f59e0b",
        compactMode: false,
        showTooltips: true,
        animationsEnabled: true,
        sidebarWidth: 256,
        panelLayout: "auto",
        showLineNumbers: true,
        showMinimap: true,
        fontSize: "medium",
        density: "comfortable",
    },
    backupSettings: {
        enableAutoBackup: false,
        backupInterval: 24,
        maxBackups: 10,
        backupLocation: "",
        includeSecrets: false,
        compressBackups: true,
        cloudSync: {
            enabled: false,
        },
    },
    kubernetesVersion: ""
});
exports.createDefaultSettings = createDefaultSettings;
